spring:
  datasource:
    url : jdbc:mysql://localhost:3306/could_vendor?useSSL=false
    username : root
    password : Dinesh@12345

#JPA Setting
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true